USE DATABASE DEMO;
USE SCHEMA CLAIMS_DEMO;

SET START_DATE = '2026-05-01';
SET END_DATE = '2027-04-30';

CREATE TABLE IF NOT EXISTS CRUCIBLE_STRESS_PURCHASES (
  USER_ID VARCHAR NOT NULL,
  PURCHASE_PRICE INTEGER NOT NULL,
  TS BIGINT NOT NULL,
  DS DATE NOT NULL
)
CLUSTER BY (DS);

CREATE TABLE IF NOT EXISTS CRUCIBLE_STRESS_CHECKOUTS (
  CHECKOUT_ID VARCHAR NOT NULL,
  USER_ID VARCHAR NOT NULL,
  TS BIGINT NOT NULL,
  DS DATE NOT NULL
)
CLUSTER BY (DS);

DELETE FROM CRUCIBLE_STRESS_PURCHASES
WHERE DS BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE);

DELETE FROM CRUCIBLE_STRESS_CHECKOUTS
WHERE DS BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE);

INSERT INTO CRUCIBLE_STRESS_PURCHASES (USER_ID, PURCHASE_PRICE, TS, DS)
WITH days AS (
  SELECT ds
  FROM (
    SELECT DATEADD(day, seq4(), TO_DATE($START_DATE)) AS ds
    FROM TABLE(GENERATOR(ROWCOUNT => 365))
  )
  WHERE ds <= TO_DATE($END_DATE)
),
generated_rows AS (
  SELECT
    d.ds,
    ROW_NUMBER() OVER (PARTITION BY d.ds ORDER BY seq4()) - 1 AS rn
  FROM days d, TABLE(GENERATOR(ROWCOUNT => 10000))
)
SELECT
  'user_' || TO_VARCHAR(1 + MOD(ABS(HASH(ds, rn)), 1000)) AS USER_ID,
  50 + MOD(ABS(HASH(ds, rn, 'purchase_price')), 5000) AS PURCHASE_PRICE,
  DATEDIFF(
    millisecond,
    '1970-01-01'::timestamp_ntz,
    DATEADD(second, MOD(rn * 17, 86400), ds::timestamp_ntz)
  ) AS TS,
  ds AS DS
FROM generated_rows;

INSERT INTO CRUCIBLE_STRESS_CHECKOUTS (CHECKOUT_ID, USER_ID, TS, DS)
WITH days AS (
  SELECT ds
  FROM (
    SELECT DATEADD(day, seq4(), TO_DATE($START_DATE)) AS ds
    FROM TABLE(GENERATOR(ROWCOUNT => 365))
  )
  WHERE ds <= TO_DATE($END_DATE)
),
generated_rows AS (
  SELECT
    d.ds,
    ROW_NUMBER() OVER (PARTITION BY d.ds ORDER BY seq4()) - 1 AS rn
  FROM days d, TABLE(GENERATOR(ROWCOUNT => 8000))
)
SELECT
  'checkout_' || TO_CHAR(ds, 'YYYYMMDD') || '_' || LPAD(TO_VARCHAR(rn), 8, '0') AS CHECKOUT_ID,
  'user_' || TO_VARCHAR(1 + MOD(ABS(HASH(ds, rn, 'checkout_user')), 1000)) AS USER_ID,
  DATEDIFF(
    millisecond,
    '1970-01-01'::timestamp_ntz,
    DATEADD(second, MOD(rn * 23, 86400), ds::timestamp_ntz)
  ) AS TS,
  ds AS DS
FROM generated_rows;

SELECT
  'CRUCIBLE_STRESS_PURCHASES' AS TABLE_NAME,
  DS,
  COUNT(*) AS ROW_COUNT
FROM CRUCIBLE_STRESS_PURCHASES
WHERE DS BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
GROUP BY DS
UNION ALL
SELECT
  'CRUCIBLE_STRESS_CHECKOUTS' AS TABLE_NAME,
  DS,
  COUNT(*) AS ROW_COUNT
FROM CRUCIBLE_STRESS_CHECKOUTS
WHERE DS BETWEEN TO_DATE($START_DATE) AND TO_DATE($END_DATE)
GROUP BY DS
ORDER BY TABLE_NAME, DS;
